import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Play } from "next/font/google";
import "./globals.css";

const play = Play({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-play"
});

export const metadata = {
  title: "Quang Long Tran",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${play.variable} overflow-x-hidden relative`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
